import type { HiringReport } from "@/lib/types/report";

/**
 * Generate a Markdown string containing every section of the hiring report.
 */
export function generateMarkdown(report: HiringReport): string {
  const lines: string[] = [];

  const push = (...l: string[]) => lines.push(...l);

  /* ── Title ── */
  push(`# GitHire Report — @${report.username}`, "");

  /* ── Profile ── */
  push("## Profile", "");
  push(`| Field | Value |`);
  push(`| --- | --- |`);
  push(`| **Name** | ${report.name || "—"} |`);
  push(`| **Username** | @${report.username} |`);
  push(`| **Bio** | ${report.bio || "—"} |`);
  push(`| **Avatar** | ${report.avatarUrl || "—"} |`);
  push(`| **Public Repos** | ${report.publicRepos} |`);
  push(
    `| **Followers** | ${report.followers >= 1000 ? `${(report.followers / 1000).toFixed(0)}k` : report.followers} |`,
  );
  push("");

  /* ── Recommended role(s) ── */
  if (report.recommendedRoles?.length) {
    push("## Recommended role(s)", "");
    for (const role of report.recommendedRoles) push(`- ${role}`);
    push("");
  }

  /* ── Executive Summary ── */
  push("## Executive Summary", "");
  push(report.executiveSummary || "—", "");

  /* ── Overall Hiring Score ── */
  push("## Overall Hiring Score", "");
  push(`**${report.overallScore} / 100**`, "");

  /* ── Hiring Decision ── */
  push("## Hiring Decision", "");
  push(`**Verdict:** ${report.verdict}`, "");
  push(report.verdictReasoning || "—", "");

  /* ── Score Breakdown ── */
  push("## Score Breakdown", "");
  push(`| Category | Score |`);
  push(`| --- | ---: |`);
  const scoreLabels: { key: keyof typeof report.scores; label: string }[] = [
    { key: "codeQuality", label: "Code Quality" },
    { key: "consistency", label: "Consistency" },
    { key: "impact", label: "Impact" },
    { key: "documentation", label: "Documentation" },
    { key: "testing", label: "Testing" },
  ];
  for (const { key, label } of scoreLabels) {
    push(`| ${label} | ${report.scores[key]} |`);
  }
  push("");

  /* ── Top Strengths ── */
  push("## Top Strengths", "");
  if (report.strengths.length > 0) {
    for (const s of report.strengths) push(`- ${s.label}`);
  } else {
    push("— None listed");
  }
  push("");

  /* ── Growth Areas ── */
  push("## Growth Areas", "");
  if (report.weaknesses.length > 0) {
    for (const w of report.weaknesses) push(`- ${w.label}`);
  } else {
    push("— None listed");
  }
  push("");

  /* ── Skills ── */
  push("## Skills", "");
  push(`| Skill | Score |`);
  push(`| --- | ---: |`);
  for (const s of report.skills) {
    push(`| ${s.skill} | ${s.value} |`);
  }
  push("");

  /* ── Technical Highlights ── */
  push("## Technical Highlights", "");
  if (report.highlights.length > 0) {
    for (const h of report.highlights) push(`- ${h}`);
  } else {
    push("— None listed");
  }
  push("");

  /* ── Activity / Commit Velocity ── */
  push("## Activity / Commit Velocity", "");
  push(`| Month | Commits |`);
  push(`| --- | ---: |`);
  for (const a of report.activity) {
    push(`| ${a.month} | ${a.commits} |`);
  }
  push("");

  push("---", "");
  push(`*Generated by GitHire on ${new Date().toLocaleDateString()}*`);

  return lines.join("\n");
}

/**
 * Trigger a browser download of the given Markdown content.
 */
export function downloadMarkdown(report: HiringReport): void {
  const md = generateMarkdown(report);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `GitHire-Report-${report.username}.md`;
  document.body.appendChild(a);
  a.click();

  // Cleanup
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 100);
}
